version: '3'

services:
  ace-rate-fetcher:
    build: .
    container_name: ace-rate-fetcher
    restart: always
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./logs:/app/logs
      # Uncomment to mount configuration file for easy updates
      # - ./providers.json:/app/providers.json
    healthcheck:
      test: ["CMD", "test", "-f", "/app/logs/rate_fetcher.log"]
      interval: 1m
      timeout: 10s
      retries: 3 